### ISSUE TITLE
New Release of gt-process-spatialstatistics

### ISSUE THREAD

**Issue by mores** [mapplus/spatial_statistics_for_geotools_udig#13]
The only non-snapshot versions of gt-process-spatialstatistics on sourceforge are:
11.2
14.5

Can you release a 22.2 version ?
Or a 21.3 version ?

**Comment by mapplus** [comment]
@mores 

Please, Use these two files: gt-process-spatialstatistics-22-SNAPSHOT.jar and gt-process-spatialstatistics-21-SNAPSHOT.jar. 

These two files are normally compatible with the version you want.
