### ISSUE TITLE
PointStatistics SLD doesn't work

### ISSUE THREAD

**Issue by serkkan86** [mapplus/spatial_statistics_for_geotools_udig#4]
First of all thanks for your great work. It's a very useful library. I am having a problem with pointstatistics sld which is among your samples.  I am having problems adding the pointFeatures parameter. How can I make this SLD workable? 

Your sld sample is:
`<?xml version="1.0" encoding="UTF-8"?><sld:StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:sld="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" version="1.0.0">
  <sld:NamedLayer>
    <sld:Name>Default Styler</sld:Name>
    <sld:UserStyle>
      <sld:Name>Default Styler</sld:Name>
      <sld:Title>Point Statistics</sld:Title>
      <sld:Abstract>Point Statistics</sld:Abstract>
      <sld:FeatureTypeStyle>
        <sld:Name>name</sld:Name>
        <sld:Transformation>
          <ogc:Function name="statistics:PointStatistics">
            <ogc:Function name="parameter">
              <ogc:Literal>polygonFeatures</ogc:Literal>
            </ogc:Function>
            <ogc:Function name="parameter">
              <ogc:Literal>pointFeatures</ogc:Literal>
              <ogc:Function name="env">
                <ogc:Literal>pointFeatures</ogc:Literal>
                <ogc:Literal>foss:stores</ogc:Literal>
              </ogc:Function>
              <ogc:Function name="parameter">
                <ogc:Literal>countField</ogc:Literal>
                <ogc:Literal>cnt</ogc:Literal>
              </ogc:Function>
            </ogc:Function>
          </ogc:Function>
        </sld:Transformation>
        <sld:Rule>
          <sld:Name>Polygon</sld:Name>
          <sld:Title>Polygon</sld:Title>
          <sld:PolygonSymbolizer>
            <sld:Stroke>
              <sld:CssParameter name="stroke">#778899</sld:CssParameter>
              <sld:CssParameter name="stroke-width">0.5</sld:CssParameter>
            </sld:Stroke>
          </sld:PolygonSymbolizer>
        </sld:Rule>
      </sld:FeatureTypeStyle>
    </sld:UserStyle>
  </sld:NamedLayer>
</sld:StyledLayerDescriptor>`

The error is: 

Rendering process failed
Could not convert the value [foss:stores, {countField=cnt}] into the expected type interface org.geotools.data.simple.SimpleFeatureCollection for parameter pointFeatures
```

**Comment by mapplus** [comment]
GeoServer rendering transformation does not yet support  more than one features at a time.

More info: http://geoserver.geo-solutions.it/edu/en/wps/rendering_tx.html
