### ISSUE TITLE
Maven build broken: Add recommended JAI-EXT repository

### ISSUE THREAD

**Issue by ctu0815** [mapplus/spatial_statistics_for_geotools_udig#5]
The Maven build of _process-spatialstatistics_ is broken due to unresolved dependencies of JAI-EXT.
Adding the recommended repository to _GeoTools/process-spatialstatistics/pom.xml_ may fix this issue:
```
<repository>
  <id>geosolutions</id>
  <name>GeoSolutions Repository</name>
  <url>http://maven.geo-solutions.it</url>
  <snapshots>
    <enabled>false</enabled>
  </snapshots>
</repository>
```

**Comment by mapplus** [comment]
@ctu0815 Thanks!
