### ISSUE TITLE
How to use this in latest geoserver2.15?

### ISSUE THREAD

**Issue by chakravarthi-vl** [mapplus/spatial_statistics_for_geotools_udig#9]

**Comment by mapplus** [comment]
@chakravarthi-vl 

Please, Visit https://sourceforge.net/projects/mango-spatialstatistics/files/GeoServer/
and download the file for your version of GeoServer.

**Comment by chakravarthi-vl** [comment]
@mapplus  thanks for the reply,
I download 2.15 version file's and added files, but in wps Demo list your service's are not displaying let me know is there any other .jar file to be added along with gs-wps-spatialstatistics-2.15-SNAPSHOT.jar, gt-process-spatialstatistics-21-SNAPSHOT.jar.

**Comment by mapplus** [comment]
@chakravarthi-vl 
I fixed an issue, Please reinstall GeoServer-Extension-OpenGxT-2.15.x.zip.
Thanks for your report.

**Comment by chakravarthi-vl** [comment]
@mapplus thanks for the reply,
Right now it's working.
I have a small query, is there any **GroupByAttributes** feature like gs:Aggregate in statistics:PointStatistics

**Comment by chakravarthi-vl** [comment]
> @chakravarthi-vl
> I fixed an issue, Please reinstall GeoServer-Extension-OpenGxT-2.15.x.zip.
> Thanks for your report.

**Comment by mapplus** [comment]
# Input parameters
statisticsFields:
  - String Field Function: First, Last
  - Numeric Field Function: Sum, Mean, Min, Max, Std, Var, Range, Count
  
  - AggregationFunction.FieldName
  - Ex) Sum.pop, Max.pop, Min.pop
  - Use comma separated list for multiple funstions

# Output field name
FST_FieldName
LST_FieldName
SUM_FieldName
AVG_FieldName
MIN_FieldName
MAX_FieldName
STD_FieldName
VAR_FieldName
RNG_FieldName
CNT_FieldName

**Comment by chakravarthi-vl** [comment]
@mapplus thanks for the reply,
I understand Existing field's, I am asking for in **gs:Aggregate**  wps service there is **GroupByAttributes** for point layer, Is there any way we can implement **GroupByAttributes** of point layer in **statistics:PointStatistics**.

**Comment by mapplus** [comment]
@chakravarthi-vl  If you want to implement a custom process, see the following URL.
  - https://docs.geoserver.org/latest/en/developer/programming-guide/wps-services/implementing.html
  - https://docs.geoserver.org/stable/en/user/community/scripting/overview.html

**Comment by chakravarthi-vl** [comment]
@mapplus thanks for the reply,
